# IRIS Multi-Classification

We have a famous iris dataset. We are going to implement classification using Neural Network

In [1]:
import numpy as np
import pandas as pd

In [4]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [5]:
df=pd.read_csv("Iris.csv")

In [7]:
df=df.drop(columns="Id")

In [9]:
dfvalues=df.values

In [15]:
X = dfvalues[:,0:4].astype(float)
Y=dfvalues[:,4]

In [18]:
X[1]

array([4.9, 3. , 1.4, 0.2])

In [19]:
Y[1]

'Iris-setosa'

As we can see, the output values are in Y and are in the form of strings. It is best practice to convert these strings into values.In this dataset there are three different classes in outputs - 'Iris-setosa','Iris-versicolor','Iris-virginica'. We can convert them into integers and then to binary matrix representing each instance using hot encoding.

Step 1: creating values for the classes

In [21]:
encoder=LabelEncoder()
encoder.fit(Y)
encoded_y=encoder.transform(Y)
encoded_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Step 2: One-hot encoding , creating the binary matrix

In [22]:
dummy_y=np_utils.to_categorical(encoded_y)
dummy_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# Build Neural Network

Softmax is used as activation function on the output layer since our output values should be of 0 and 1 and used to predict.
Adam GD is efficiant and a logarithmic function also called as categorical crossentropy
The ReLu activation function is used since we have hot encoded our classes. And ReLu provides the class by taking into account the max value produced for an output value

# ReLu(Rectified Linear Activation)
if input > 0:
	return input
else:
	return 0

g(z) = max{0, z}

# Softmax Activation Function
Softmax function is used for activation. It is the softer version of argmax.Argmax provides the index of the highest value directly.Softmax provides the probabilistic version of argmax by scaling the values

probability = exp(value) / sum v in list exp(v)

Eg: if target vector is [0, 1, 0]

softmax would give [0.09003057 0.66524096 0.24472847]

In [28]:
def baseline_model():
    model=Sequential()
    model.add(Dense(8,input_dim=4,activation='sigmoid'))
    model.add(Dense(3,activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    return model

In [29]:
estimator=KerasClassifier(build_fn=baseline_model,epochs=200,batch_size=5,verbose=0)

/Users/keerthiseetha/villanova/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


In [30]:
#evaluating the nn model
kfold=KFold(n_splits=10,shuffle=True)

In [31]:
result=cross_val_score(estimator,X,dummy_y,cv=kfold)

NameError: name 'results' is not defined

In [35]:
print("Accuracy: %.2f%% (%.2f%%)" % (result.mean()*100, result.std()*100))

Accuracy: 96.67% (3.33%)
